package com.ouvrirdeveloper.domain.models
import kotlinx.serialization.Serializable

@Serializable
data class RequisitionDetail(
    val reqesitionID: Long,
    val reqNumber: String,
    val reqDate: String,
    val pAprojid: String,
    val paprojname: String,
    val deliveryAddress: String,
    val contactPerson: String,
    val contactNumber: String,
    val lastModifiedBy: String,
    val send: String,
    val approved: String,
    val approvedBy: String,
    val approvalComments: String,
    val slNo: Long,
    val materialCode: String,
    val materialName: String,
    val brand: String,
    val consltapproval: String,
    val costCode: String,
    val uom: String,
    val quantity: Long,
    val requiredDate: String,
    val remarks: String,
    val deliveryRemarks: String,
    val boqReference: String,
    val revised: Long,
    val revision: Long,
    val revisionDate: String,
    val sendBy: String,
    val readyForPO: String,
    val purchaseOfficer: String,
    val poqtystatus: Long,
    val cancelQuantity: Long,
    val cancelComments: String,
    val createdBy: String,
    val createdOn: String,
    val mrStatus: String,
    val approvedDate: String
)