plugins {
    id(Plugins.androidLibrary)
    id(Plugins.kotlinKapt)
    id(Plugins.kotlinAndroid)
    id(Plugins.modulePlugin)
}
addMoshi()
addKoin()
addCoil()
addDomain()
addMaterial()
addNavigation()
addFragment()
addTimber()
addLogger()
addRoom()
addPaging()
addLottie()